from models.paciente import Paciente
from models.profissional import Profissional
from models.internacao import Internacao
from models.consulta import Consulta
from models.usuario import Usuario
from models.notificacao import Notificacao
from models.teleconsulta import Teleconsulta
from models.prescricao import Prescricao
from models.prontuario import Prontuario
